"""Precompute fault-equivalent ZX diagrams for the demo's recursive 'ZX diagram' tab.

The browser can't run Python, so at build time we run pyzx's recursive_unfuse_FE
(vendored from zxcalc/pyzx master at experimental/unfuse_FE_rules.py — the
installed pyzx 0.9.0 predates the rewrite_rules module) over the slider grid and
bundle the resulting graph *structure* (vertex types + coordinates and edges)
into docs/recursive_zx_data.js. app.js redraws it with the site's SVG infra.

For a CAT^n state we start from a single phase-0 Z-spider connected to n boundary
outputs, then call recursive_unfuse_FE(g, v, w=t). This recursively unfuses the
high-degree spider into a w(=t)-fault-equivalent diagram of degree-<=3 spiders
(arXiv:2506.17181). pyzx assigns a (qubit, row) coordinate to every vertex during
unfusion, so we keep those coordinates and the diagram matches pyzx's own layout.
"""

import json
import os
import sys
import warnings

import pyzx as zx
from pyzx.utils import VertexType

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "experimental"))
from unfuse_FE_rules import recursive_unfuse_FE  # noqa: E402

# Slider ranges from docs/index.html: #nRange (8..50) and #tRange (2..7). Here t
# maps directly to the unfusion's fault weight w (no CAT^4-base clamp — that
# clamp belongs to the stim recursive_construction, not the ZX unfusion).
N_RANGE = range(8, 51)
T_RANGE = range(2, 8)

OUT_PATH = os.path.join(os.path.dirname(__file__), "recursive_zx_data.js")


def unfused_structure(n: int, t: int) -> dict:
    g = zx.Graph()
    centre = g.add_vertex(VertexType.Z, qubit=(n - 1) / 2.0, row=0)
    outputs = []
    for i in range(n):
        b = g.add_vertex(VertexType.BOUNDARY, qubit=i, row=2)
        g.add_edge((centre, b))
        outputs.append(b)
    g.set_outputs(tuple(outputs))

    if not recursive_unfuse_FE(g, centre, w=t):
        raise RuntimeError(f"recursive_unfuse_FE failed for n={n}, t={t}")

    index = {vt: i for i, vt in enumerate(g.vertices())}
    verts = [
        [int(g.type(vt)), round(float(g.qubit(vt)), 3), round(float(g.row(vt)), 3)]
        for vt in g.vertices()
    ]
    edges = []
    for e in g.edges():
        a, b = g.edge_st(e)
        edges.append([index[a], index[b], int(g.edge_type(e))])
    return {
        "v": verts,                       # [type, qubit, row] — type 0=boundary,1=Z,2=X
        "e": edges,                       # [vertexIdxA, vertexIdxB, edgeType] — 1=simple,2=hadamard
        "o": [index[o] for o in g.outputs()],
        "nSpiders": sum(1 for vt in g.vertices() if g.type(vt) != VertexType.BOUNDARY),
    }


def main() -> None:
    warnings.filterwarnings("ignore")
    table = {}
    for n in N_RANGE:
        table[str(n)] = {}
        for t in T_RANGE:
            table[str(n)][str(t)] = unfused_structure(n, t)
        print(f"n={n}: {table[str(n)]['7']['nSpiders']} spiders at t=7 "
              f"(t={list(T_RANGE)})")

    payload = {
        "nRange": [N_RANGE.start, N_RANGE.stop - 1],
        "tRange": [T_RANGE.start, T_RANGE.stop - 1],
        "vertexTypes": {"boundary": 0, "Z": 1, "X": 2},
        "edgeTypes": {"simple": 1, "hadamard": 2},
        "table": table,
    }
    with open(OUT_PATH, "w") as f:
        f.write("// Auto-generated by docs/build_recursive_zx.py — do not edit by hand.\n")
        f.write("// Fault-equivalent ZX diagrams from pyzx recursive_unfuse_FE\n")
        f.write("// (zxcalc/pyzx unfuse_FE_rules.py); see arXiv:2506.17181.\n")
        f.write("window.SPIDERCAT_RECURSIVE_ZX = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")
    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"\nWrote {OUT_PATH} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
