"""Precompute recursive-construction decompositions for the static demo site.

The browser can't run Python, so we run experimental/recursive_construction.py
here (at build time), once per slider point (n, t), and bundle each stim
timeline-text decomposition into docs/recursive_decompositions.js.

The recursive construction produces a cat of size 2^k * nBase (nBase = 4, the
paper's CAT^4 seed), which is always a power of two. When the requested n is not
a power of two we round UP to n' = the smallest power of two >= n and run the
script for n'. The n' - n wires beyond the requested size are "added" wires; we
terminate each of them with a Z spider — i.e. a Z-basis measurement (M), which is
exactly a Z-spider effect in ZX — so stim draws a terminator box at the end of
each added wire. The added wires are the highest indices q_n .. q_{n'-1}.

t is clamped to nBase - 1 (transversal ZZ needs t + 1 <= the base block size),
mirroring the .py's own clamp, so distinct decompositions only exist for the
effective t in {2, 3}.
"""

import io
import json
import os
import sys
from contextlib import redirect_stdout

import stim

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "experimental"))
from recursive_construction import recursive_construction  # noqa: E402

N_BASE = 4
# Slider range in docs/index.html (#nRange) and the effective t values.
N_RANGE = range(8, 51)
EFFECTIVE_T_VALUES = [2, 3]  # min(slider_t, N_BASE - 1)

OUT_PATH = os.path.join(os.path.dirname(__file__), "recursive_decompositions.js")


def next_power_of_two(n: int) -> int:
    p = 1
    while p < n:
        p <<= 1
    return p


def decomposition_for(n: int, t: int) -> dict:
    n_prime = next_power_of_two(n)
    k = (n_prime // N_BASE).bit_length() - 1  # log2(n_prime / N_BASE)
    assert N_BASE * (2 ** k) == n_prime, (n, n_prime, k)

    # The function prints progress + the diagram; suppress that and render the
    # returned circuit ourselves so we control exactly what the diagram shows.
    with redirect_stdout(io.StringIO()):
        circ = recursive_construction(n=N_BASE, k=k, t=t, use_flags=False)

    # Terminate each added wire q_n .. q_{n'-1} with a Z spider (Z-basis
    # measurement). Appending M also forces these qubits into the diagram even
    # when the bare construction never touched them.
    added_wires = list(range(n, n_prime))
    if added_wires:
        circ.append("M", added_wires)

    diagram = str(circ.diagram("timeline-text"))
    return {
        "n": n,
        "nPrime": n_prime,
        "k": k,
        "tEffective": t,
        "numQubits": circ.num_qubits,
        "numMeasurements": count_zz(circ),
        "addedWires": added_wires,
        "diagram": diagram,
    }


def count_zz(circ: stim.Circuit) -> int:
    # CZ instructions merge into one with many targets, so count target pairs.
    total = 0
    for inst in circ:
        if inst.name == "CZ":
            total += len(inst.targets_copy()) // 2
    return total


def main() -> None:
    table = {}
    for n in N_RANGE:
        table[str(n)] = {}
        for t in EFFECTIVE_T_VALUES:
            entry = decomposition_for(n, t)
            table[str(n)][str(t)] = entry
        sample = table[str(n)]["3"]
        print(f"n={n} -> n'={sample['nPrime']} (k={sample['k']}), "
              f"{len(sample['addedWires'])} added wires (Z spiders)")

    payload = {
        "nBase": N_BASE,
        "nRange": [N_RANGE.start, N_RANGE.stop - 1],
        "table": table,
    }
    with open(OUT_PATH, "w") as f:
        f.write("// Auto-generated by docs/build_recursive_decompositions.py — do not edit by hand.\n")
        f.write("// Decompositions printed by experimental/recursive_construction.py.\n")
        f.write("// Each diagram is for n' = next power of two >= n; the n' - n added\n")
        f.write("// wires are terminated with Z spiders (Z-basis measurements, shown as M).\n")
        f.write("window.SPIDERCAT_RECURSIVE_DECOMP = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")
    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"\nWrote {OUT_PATH} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
